config/routes.rb
Rails.application.routes.draw do
  resources :entrees do 
    resources :desserts
  end
  root "entrees#index"

end

app/models/dessert.rb
class Dessert < ActiveRecord::
  validates_presence_of :sweet, :choco, :words
  belongs_to :entree
end

app/models/entree.rb
class Entree < ActiveRecord::Base
    validates_presence_of :food, :menu, :description
    has_many :dessert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entrees_controller.rb
class EntreesController < ApplicationController
  before_action :set_entree, only: [:show, :edit, :update, :destroy]

  # GET /entrees
  # GET /entrees.json
  def index
    @entrees = Entree.all
  end

  # GET /entrees/1
  # GET /entrees/1.json
  def show
  end

  # GET /entrees/new
  def new
    @entree = Entree.new
  end

  # GET /entrees/1/edit
  def edit
  end

  # POST /entrees
  # POST /entrees.json
  def create
    @entree = Entree.new(entree_params)

    respond_to do |format|
      if @entree.save
        format.html { redirect_to @entree, notice: 'Entree was successfully created.' }
        format.json { render :show, status: :created, location: @entree }
      else
        format.html { render :new }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrees/1
  # PATCH/PUT /entrees/1.json
  def update
    respond_to do |format|
      if @entree.update(entree_params)
        format.html { redirect_to @entree, notice: 'Entree was successfully updated.' }
        format.json { render :show, status: :ok, location: @entree }
      else
        format.html { render :edit }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrees/1
  # DELETE /entrees/1.json
  def destroy
    @entree.destroy
    respond_to do |format|
      format.html { redirect_to entrees_url, notice: 'Entree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entree
      @entree = Entree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entree_params
      params.require(:entree).permit(:food, :menu, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrees_helper.rb
module EntreesHelper
end

app/views/entrees/_form.html.erb
<%= form_for(@entree) do |f| %>
  <% if @entree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entree.errors.count, "error") %> prohibited this entree from being saved:</h2>

      <ul>
      <% @entree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food %><br>
    <%= f.text_field :food %>
  </div>
  <div class="field">
    <%= f.label :menu %><br>
    <%= f.number_field :menu %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entrees/edit.html.erb
<h1>Editing Entree</h1>

<%= render 'form' %>

<%= link_to 'Show', @entree %> |
<%= link_to 'Back', entrees_path %>

app/views/entrees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entrees</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Menu</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrees.each do |entree| %>
      <tr>
        <td><%= entree.food %></td>
        <td><%= entree.menu %></td>
        <td><%= entree.description %></td>
        <td><%= link_to 'Show', entree %></td>
        <td><%= link_to 'Edit', edit_entree_path(entree) %></td>
        <td><%= link_to 'Destroy', entree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entree', new_entree_path %>

app/views/entrees/new.html.erb
<h1>New Entree</h1>

<%= render 'form' %>

<%= link_to 'Back', entrees_path %>

app/views/entrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @entree.food %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @entree.menu %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entree.description %>
</p>

<%= link_to 'Edit', edit_entree_path(@entree) %> |
<%= link_to 'Back', entrees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodMenu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>